src/hooks/useCarouselController.tsx

Not calling the "optional" Callback on JS Thread breaks with Reanimated2 and crashes the host app when #ref.goToIndex(...)

Fix: Callback is not called on JS Thread

---

src/layouts/ParallaxLayout.tsx
src/layouts/parallax.ts

I added the "parallaxAdjacentItemScale" property to the parallax layout. The property is intended to allow the user to customize the size of items adjacent to the item in focus.
PS: Sorry, I couldn't find the template for PR.

feat: added "parallaxAdjacentItemScale" property into parallax layout

---

README.md

Added a tip in README with explanations and related issue to help users who want to free one of the axes when using Carousel inside a ScrollView/FlatList. For more details and use case, see https://github.com/dohooo/react-native-reanimated-carousel/issues/143
Sorry, my Chinese is not up to date, I ask someone to translate the README.

Added tip for better UX when Carousel within scroll

---

src/Carousel.tsx
src/hooks/useCarouselController.tsx

**Problems:**
1. If I set the X value to defaultIndex, when "onScrollEnd" is invoked the "previous" parameter is not the X value but 0.
2. #156
**Correction:**
I noticed that defaultIndex was only used to define the carousel view, it wasn't updating the UI bridge or the module's internal references.
All I did was make the default value of bridge and refs defaultIndex.

fix: "defaultIndex" wasn't define internal values (UI bridge and refs)

---

README.md
README.zh-CN.md

There was a typo in the README of this repo, incorrectly referring to a `FlastList` component instead of the `FlatList` component.

docs: fix FlatList typo in README

---

exampleExpo/src/pages/parallax/index.tsx

I was facing issues in smaller devices. Some part of carousel remained hidden. By adding the width in style prop fixed the issue. And multiplying it with 0.86 gave the best result.

Parallax Horizontal Center Align

---

exampleBare/metro.config.js

There is a metro related error in the blacklist module, the name of the dir was changed and an error was found running the base `yarn` command, This is an update to this problem.

Metro config blacklist fix

---

.changeset/gold-onions-chew.md
src/components/BaseLayout.tsx
src/components/Carousel.tsx
src/components/ItemRenderer.tsx
src/hooks/useOffsetX.test.ts
src/hooks/useVisibleRanges.tsx

Before, even if the limit of the number of render is set, it will render one more layer of BaseLayout, which makes the performance can not be maximized, and now the optimization makes BaseLayout will not render any more, even if the number of data is 1 million, it will only render the specified amount of render. Performance has improved dramatically.
fix #352, fix #362, fix #258, fix #478

perf: reduce the amount of work done when rendering data

---

.changeset/violet-buckets-act.md
example/website/pages/props.mdx
src/components/ScrollViewGesture.tsx
src/types.ts

Add a new props `minScrollDistancePerSwipe` to set the minimum scroll instance to make carousel scroll.

feat: add a new props `minScrollDistancePerSwipe`

---

src/components/ScrollViewGesture.tsx

When `endWithSpring` is called, it is using the _previous_ values for `scrollEndVelocity` and `scrollEndTranslation` (rather than the values just set in `onGestureEnd`). This seems to cause strange carousel behavior for the user: the function isn't using the values from the most recent pan.
From the user's standpoint, the problem is very obvious (and potentially frustrating) when the user pans one direction, then reverses direction for their next pan. (**Please see video demonstration below**.)
This is due to updates to shared values created via `useSharedValue()` updating asynchronously (see https://docs.swmansion.com/react-native-reanimated/docs/core/useSharedValue#remarks ).
Rather than relying on the shared data variable between function calls, let's explicitly pass the values as …

fix: `onGestureEnd` -> `endWithSpring` uses outdated data via `useSharedValue`

---

src/components/Pagination/Basic/index.tsx

Import TouchableWithoutFeedback from react-native instead of react-native-gesture-handler to solve Error: NativeViewGestureHandler must be used as a descendant of GestureHandlerRootView

Change TouchableWithoutFeedback import

---

src/components/ScrollViewGesture.tsx

we updated react-native-reanimated-carousel to version `v4.0.0-alpha.12` in our project and ran into this type error in `ScrollViewGesture.tsx`:
added a null check to the MeasuredDimension, with a default of `0`

fix: typescript error where MeasuredDimension can be null

---

.changeset/nine-moose-whisper.md
src/hooks/useOnProgressChange.ts

On iOS, when running in "Release" configuration (i.e. not "development" configuration), if `onProgressChange` is a function, **the app crashes**. 😖
On Android, similar **crash**. Thanks to @yannick-softwerft for providing a traceback in [a comment below](https://github.com/dohooo/react-native-reanimated-carousel/pull/648#issuecomment-2256481543).
This bug was accidentally introduced in 0d2b930f394f65fd70a03593ea8c7b16fb552e62 (in [code here](https://github.com/dohooo/react-native-reanimated-carousel/commit/0d2b930f394f65fd70a03593ea8c7b16fb552e62#diff-76055baf1d987bd60cfcbc19200ec53038a6ee44972a224e112ad5869528779bR46-R50))
Since the callback functions in `useAnimatedReaction` [are automatically workletized](https://docs.swmansion.com/react-native-reanimated/docs/advanced/useAnimatedReacti …

fix: typeof "function" onProgressChange - fixes app crash

---

.changeset/spotty-melons-return.md
src/components/ScrollViewGesture.tsx

When `onGestureUpdate` is called, it may be using the _previous_ value for `panOffset` (rather than the value just set in `onGestureStart`). This seems to cause a flicker on slow devices since a `translation` is shown that is from a different screen.
I see this flicker most obviously on my Android simulator (**please see video demonstration below**), but the problem exists on other devices as well.
This is due to updates to shared values created via `useSharedValue()` updating asynchronously (see https://docs.swmansion.com/react-native-reanimated/docs/core/useSharedValue/#remarks ).
This flicker seemed to get worse after this commit https://github.com/dohooo/react-native-reanimated-carousel/commit/b654f439e905bc1d45f5cbb1fd291f3a82848368 - "**feat: replaced onScrollBegin with …

fix: flicker when starting pan: `panOffset` value race condition

---

example/website/pages/props.mdx

1. It provides a complete, runnable example demonstrating the use of `useRef` with the `Carousel` component in React Native.
2. It explains each step of the code with clear and concise comments.
3. It uses separate code blocks for JavaScript, TypeScript, and JSX, making it easier to read and understand.
4. It shows how to import the necessary types for TypeScript, which is important for maintaining consistency and avoiding errors.
5. It covers both JavaScript and TypeScript cases, making it more inclusive for different development preferences.
6. It presents a practical use case (navigating between slides) that helps better understand the application of `useRef`.

Feature/Docs: Add a explained documentation to the Ref section in Props page.

---

example/app/src/pages/parallax/index.tsx
src/components/Pagination/Custom/PaginationItem.tsx
src/components/Pagination/Custom/index.tsx
src/components/Pagination/index.tsx

I'm adding Paging.Custom dot animation, it is for my personal project but I contribute here since I think it may helps someone.
By default, it will takes `width, height, borderRadius and backgroundColor` from `dotStyle` and `activeDotStyle` and create animation from them.
I also provide a function that user can use to add custom animated style:
```
customReanimatedStyle?: (
progress: number,
index: number,
length: number,
) => DefaultStyle
```
Below is the example how we use it (The 2 last paging dots):
<video src="https://github.com/user-attachments/assets/056382c6-b781-4de6-a30b-4b4a178ac260" width="320" controls></video>
Please take a look, thank you!

add Pagination.Custom dot animation

---

.changeset/many-ads-fry.md
src/hooks/usePanGestureProxy.test.tsx
src/hooks/usePanGestureProxy.ts

The `onStart`, `onUpdate`, and `onEnd` gesture handlers are not being automatically workletized. This causes these handlers to run on the JS thread instead of the UI thread, and this is causing a number of issues, including animations running more slowly and some data (via `useSharedData`) being set asynchronously, leading to some race conditions.
(See more discussion below in "Discussion of the bug".)
Add `"worklet"` directives for each gesture handler function.
The tests (in `src/hooks/usePanGestureProxy.test.tsx`) also include `onBegin` and `onFinalize` handlers. Since the tests include these, I decided to add some functions to support them in `src/hooks/usePanGestureProxy.ts` using the same method as for `onStart`, `onUpdate`, and `onEnd`.
If some handlers for a given gesture are …

fix: gesture `onStart`, `onUpdate`, and `onEnd` (et al) should be worklets

---

src/hooks/useAutoPlay.ts

Hi folks,
I'm currently utilizing this fantastic library but encountering frame rate drops. When using a parallax carousel with `autoPlay`, the FPS tends to drop during the transition of each slide. This results in a non-smooth scroll, especially when the carousel is embedded within a `ScrollView` or a complex layout with numerous images.
After some research, I found that switching to `requestAnimationFrame` to handle autoplay in the `useAutoPlay` hook could help reduce frame skipping. Here's a demo showcasing the changes:
Test info:
```
simulator: Pixel 6 Pro API 34
```
* Before:
https://github.com/dohooo/react-native-reanimated-carousel/assets/51257500/30ca32b6-e8f6-4f3a-82dc-e5aa7b57d908
* After
https://github.com/dohooo/react-native-reanimated-carousel/assets/51257500/c67d1f8d-6f21-4c1 …

refactor: using requestAnimationFrame instead of setTimeout to reduce frame skipping

---

.changeset/cyan-pillows-swim.md
src/components/Pagination/Basic/PaginationItem.tsx
src/components/Pagination/Basic/index.tsx
src/components/Pagination/Custom/PaginationItem.tsx
src/components/Pagination/Custom/index.tsx

As per #676, [v4.0.0-canary.13](https://github.com/dohooo/react-native-reanimated-carousel/releases/tag/v4.0.0-canary.13) accidentally introduced a bug that caused the click events on `Pagination.Basic` to no longer work.
This appears to have been accidentally introduced in #655
Thanks to @qwertychouskie for reporting here:
- #676 
From the [TouchableWithoutFeedback](https://reactnative.dev/docs/touchablewithoutfeedback) docs:
> Importantly, `TouchableWithoutFeedback` works by cloning its child and applying responder props to it. It is therefore required that any intermediary components pass through those props to the underlying React Native component.
1. in `Pagination.Custom`, standardize by importing `TouchableWithoutFeedback` from `react-native` (like we already do for …

fix: PaginationItem onPress (both Pagination.Basic and Pagination.Custom)

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/static.yml
package.json

Update development workflow

---

example/app/app/+html.tsx
example/website/components/Demo.tsx

fix: demo app can't be displayed in doc site.

---

.changeset/rare-insects-camp.md
src/components/ScrollViewGesture.tsx

Fixes #706
In `ScrollViewGesture.tsx`, we had included `touching.value` and `scrollEndTranslation.value` in the dependency arrays for a couple of React callbacks. Not only is this not necessary, but it also causes a warning message to appear (and introduces the potential performance implication mentioned below).
These dependency array `.value`s were introduced in https://github.com/dohooo/react-native-reanimated-carousel/commit/eb21293d6c0544da9e62a418505945dc46a59cb6 (as a part of #116).
As per #706 (thank you, @joaofelippe911), a console warning appears when using react-native-reanimated version 3.16.0 or higher. This new warning was added via https://github.com/software-mansion/react-native-reanimated/pull/6310
The warning looks like:
```
WARN  [Reanimated] Reading from `value` during …
```

fix: dependency array; removes shared value access warning from react-native-reanimated

---

src/layouts/parallax.ts

This PR fixes #715, #712 
Round the zIndex value in the parallax layout
- I manually tested

fix: parallax layout with new arch enabled

---

.changeset/wise-drinks-explode.md
biome.json
example/app/app/demos/basic-layouts/left-align/index.tsx
example/app/app/demos/basic-layouts/normal/index.tsx
example/app/app/demos/basic-layouts/parallax/demo.tsx
example/app/app/demos/basic-layouts/parallax/index.tsx
example/app/app/demos/basic-layouts/stack/index.tsx
src/components/Carousel.test.tsx
src/components/ScrollViewGesture.tsx

https://github.com/dohooo/react-native-reanimated-carousel/pull/596

fix: better slow pan: if user intent is to stay on current page, _don't_ change page

---

src/components/CarouselLayout.tsx
src/components/ItemLayout.tsx
src/hooks/useOffsetX.ts

Possible relates to #625 #618 #509 
Fixes issues with web. Possible due to not using (or able to use) `react-native-reanimated/plugin` babel plugin in a project.
We tested this on our own codebase (Next.js with Expo) by applying a patch file with the same fixes.

fix: Added missing dependencies for web to work

---

src/layouts/stack.ts

Fixes https://github.com/dohooo/react-native-reanimated-carousel/issues/684
Applied the patch mentioned in https://github.com/dohooo/react-native-reanimated-carousel/issues/684#issuecomment-2431457629 so that dependent projects can stop relying on patches.

fix: #684 type error `property push does not exist on type`
