- src/Carousel.tsx
- src/useComputedAnim.ts
- src/useOffsetX.ts
> fix: solve sliding flicker problem

- example/src/App.tsx
- src/hooks/useCarouselController.tsx
> fix: quick call switch method causes an offset issue 

- example/src/App.tsx
- src/Carousel.tsx
> fix: image flickers within Carousel when state is updated

- example/src/App.tsx
- src/hooks/useOffsetX.ts
> fix: fix items position

- README.md
- README.zh-CN.md
- src/Carousel.tsx
- src/CarouselItem.tsx
- src/hooks/useOffsetX.ts
- src/hooks/useVisibleRanges.tsx
- src/layouts/ParallaxLayout.tsx
- src/utils/log.ts
> perf: reduce the calculation of animation values

- README.md
- README.zh-CN.md
- example/src/App.tsx
- src/Carousel.tsx
- src/CarouselItem.tsx
- src/ScrollViewGesture.tsx
- src/hooks/useCarouselController.tsx
- src/hooks/useIndexController.ts
- src/hooks/useOffsetX.ts
- src/hooks/usePropsErrorBoundary.ts
- src/index.tsx
- src/layouts/ParallaxLayout.tsx
- src/types.ts
> feat: vertical mode

- src/Carousel.tsx
- src/ScrollViewGesture.tsx
> fix: scroll pass the last item

- src/Carousel.tsx
- src/constants/index.ts
> fix: onProgressChange/onSnapToItem props wrong calculation

- example/src/components/SBImageItem.tsx
- example/src/normal/index.tsx
- src/Carousel.tsx
- src/hooks/useAutoPlay.ts
> refactor: refactor useAutoPlay hooks

- src/ScrollViewGesture.tsx
> fix: fix wrong offset when out of bounds

- src/layouts/normal.ts
> fix: remove ExtrapolateParameter of normal layout translate

- src/hooks/useAutoPlay.ts
- yarn.lock
> fix: when autoPlay is false, manual sliding will still autoPlay

- src/Carousel.tsx
- src/hooks/useInitProps.ts
- src/hooks/useOnProgressChange.ts
> fix: onProgressChange & onSnapToItem bug when only 2 image

- src/Carousel.tsx
- src/hooks/useOnProgressChange.ts
Try fix https://github.com/dohooo/react-native-reanimated-carousel/issues/66
> Fix: Cannot add new property '__reanimatedHostObjectRef'

- src/hooks/useCarouselController.tsx
> Fix scrollTo 0 index bug 

- README.md
Co-authored-by: gxxgcn <enjoygrant@163.com>
Co-authored-by: dohooo <zhaodonghao586@outlook.com>
> docs: ✏️ some changes

- src/hooks/useCarouselController.tsx
> Add a check for direction negative zero (251)

- README.md
- README.zh-CN.md
- docs/about.md
- docs/about.zh-CN.md
- docs/custom-animation.md
- docs/custom-animation.zh-CN.md
Updates the readme to use the correct path for the links.
> fix: update the example paths

- .changeset/lucky-tools-fly.md
- package.json
> chore: only push the lib to npm.

- .changeset/popular-tomatoes-jam.md
- exampleExpo/src/components/SButton.tsx
- exampleExpo/src/pages/normal/index.tsx
- package.json
- src/Carousel.tsx
- src/LazyView.tsx
- src/ScrollViewGesture.tsx
- src/hooks/useAutoPlay.ts
- src/index.tsx
- src/layouts/ParallaxLayout.tsx
- yarn.lock
> fix: fixed ref unusable issue

- README.md
Currently, all examples point to a "404 - page not found" :cry:
> fix: fix example URLs

- example/app/src/Home.tsx
- example/app/src/pages/right-align/index.tsx
I added the basic plain component in this PR and opened another one to update the docs website with the code and visual samples.
> Right Align complementary carousel component was added

- README.md
The image for right-align carousel was added and the README file was correctly updated
> New sample added to README 

- .changeset/stupid-points-attend.md
- .github/pull_request_template.md
- README.md
- package.json
- yarn.lock
> feat: Removed unnecessary peer dependences

- example/app/app/+html.tsx
- example/app/app/_layout.tsx
> fix: demo app can't be displayed in doc site.

- .changeset/shy-walls-clap.md
- package.json
> docs: update homepage field of package.json

- .changeset/polite-forks-rescue.md
- src/layouts/parallax.ts
> chore: code formatting and adds changeset

- .changeset/mean-needles-rhyme.md
- src/components/ItemLayout.tsx
> fix: add pointerEvents: ‘box-none’ to ItemLayout

- .changeset/modern-carpets-sleep.md
- src/components/Carousel.test.tsx
- src/components/ItemLayout.tsx
- src/components/ItemRenderer.tsx
- src/types.ts
https://github.com/dohooo/react-native-reanimated-carousel/pull/709
> feat: add index parameter to customAnimation

- src/layouts/stack.ts
> fix(bug): Loss of precision during arithmetic conversion

- .changeset/add-programmatic-control-docs.md
- example/website/pages/_meta.json
- example/website/pages/migration-v4.mdx
- example/website/pages/programmatic-control.mdx
Resolves #822 by adding comprehensive documentation for programmatic control of the carousel.
- **Clear API Reference**: Detailed documentation for `scrollTo`, `next`, `prev`, and `getCurrentIndex` methods
- **Practical Examples**: Real-world usage patterns including:
- Pagination control with dots
- Navigation buttons (prev/next)
- Dynamic content updates with proper timing
- Auto-advance carousel
- Jump to specific items by ID
- **Important Warnings**: Race condition handling and timing considerations
- **Comprehensive Typing**: Full TypeScript examples with proper types
- **No "Controlled Mode"**: Made it clear this library doesn't support React-style controlled components
- **Updated Migration Guide**: Fixed misleading "controlled mode" reference and linked to new docs
- **Imperative …
> docs: add comprehensive programmatic control documentation
